#include "pch.h"
#include "../TravelSystem/Person.h"
#include "../TravelSystem/Company.h"
#include "../TravelSystem/Transport.h"
#include "../TravelSystem/Ticket.h"
#include "../TravelSystem/Booking.h"
#include "../TravelSystem/Hotel.h"
#include "../TravelSystem/Flight.h"
#include "../TravelSystem/Destination.h"
#include "../TravelSystem/Guide.h"
#include "../TravelSystem/Tour.h"
#include "../TravelSystem/Review.h"
#include "../TravelSystem/Package.h"
#include "../TravelSystem/SupportService.h"
#include "../TravelSystem/Payment.h"
#include "../TravelSystem/Calendar.h"
#include "../TravelSystem/Person.cpp"
#include "../TravelSystem/Company.cpp"
#include "../TravelSystem/Transport.cpp"
#include "../TravelSystem/Ticket.cpp"
#include "../TravelSystem/Booking.cpp"
#include "../TravelSystem/Hotel.cpp"
#include "../TravelSystem/Flight.cpp"
#include "../TravelSystem/Destination.cpp"
#include "../TravelSystem/Guide.cpp"
#include "../TravelSystem/Tour.cpp"
#include "../TravelSystem/Review.cpp"
#include "../TravelSystem/Package.cpp"
#include "../TravelSystem/SupportService.cpp"
#include "../TravelSystem/Payment.cpp"
#include "../TravelSystem/Calendar.cpp"

int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}